#!/bin/sh

# Add the following text as a file in /usr/share/libalpm/hooks/statusbar.hook:
#[Trigger]
# Operation = Upgrade
# Type = Package
# Target = *

# [Action]
# Description = Updating statusbar...
# When = PostTransaction
# Exec = /usr/bin/pkill -RTMIN+16 dwmblocks


packages=$(pacman -Qu | wc -l)
aurpackages=$(paru -Qua | wc -l)
allpackages=$(paru -Qu | wc -l)

if [ "$allpackages" -gt 0 ];
then
	echo "📦 $packages-$aurpackages"  
fi

if [ "$packages" -gt 0 ];
then
	dunstify "Packages" "$(pacman -Qu)"
fi

if [ "$aurpackages" -gt 0 ];
then
	dunstify "AUR Packages" "$(paru -Qua)"
fi
