#! /bin/sh

currentlevel=$(pamixer --get-volume-human)
mutestatus=$(pamixer --get-mute)

if [ $currentlevel = 0% ];
then
	echo "🔇 Muted"
elif [ $mutestatus = true ];
then
	echo "🔇 Muted"
elif [ "$(echo "$currentlevel" | tr -d "%")" -le " 50" ];
then
	echo "🔉 $currentlevel"


elif [ "$(echo "$currentlevel" | tr -d "%")" -ge " 50" ];
then
	echo "🔊 $currentlevel"
fi

