#!/bin/sh

networkname=$(iw dev | awk '/ssid/ {print $2}')
networkstatus=$(cat /sys/class/net/wlp1s0/operstate)

if [ "$networkstatus" = up ]; 
then
    echo "$networkname"
else
	echo "Disconneted"
fi
