#!/bin/sh
# Simple script to output battery level formatted for polybar

bat_number=0
acpi=$(acpi -b 2>/dev/null| grep "Battery $bat_number")
mode=$(echo "$acpi" | awk '{print $3}')
percent=$(echo "$acpi" | awk '{print $4}'| grep -Eo '[0-9]*')
remaining=$(echo "$acpi" | awk '{print $5}')
symbol=""


if [ "$percent" \< 15 ]; then
  dunstify Battery level 15%
fi
