#!/bin/sh

playerstatus=$(playerctl status 2>/dev/null)

if [ "$playerstatus" = Playing ];
then
	dunstify -r 2 "$(playerctl metadata artist)" "$(playerctl metadata title)"

else 
	dunstify -r 2 "No players available"
fi
