#!/bin/sh

# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

#[ "$(printf "No\\nYes" | dmenu -h "50" -fn "SFMono Nerd Font" -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] && $2

[ "$(printf "No\\nYes" | rofi -dmenu -i -theme ~/.config/rofi/themes/rmenu.rasi -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] && $2
