#!/bin/bash

playinginfo=$(playerctl metadata --player=Lollypop --format "{{ title }}" 2>/dev/null)
playerstatus=$(playerctl status Lollypop 2>/dev/null)


if [ "$playerstatus" = Playing ];
then
	echo $playinginfo

else 
	echo ""
fi

