#! /bin/sh

currentlevel=$(pulseaudio-ctl current)
mutestatus=$(pacmd list-sinks | awk '/muted/ { print $2 }')

if [ $currentlevel = 0% ];
then
	echo "🔇 Muted"
elif [ $mutestatus = yes ];
then
	echo "🔇 Muted"
elif [ "$(echo "$currentlevel" | tr -d "%")" -le " 50" ];
then
	echo "🔉 $currentlevel"


elif [ "$(echo "$currentlevel" | tr -d "%")" -ge " 50" ];
then
	echo "🔊 $currentlevel"
fi

