#!/bin/bash

weather=$(curl -s wttr.in/Egypt?format=3)
short="$weather"

if [ $(echo "$weather" | grep -E "(Unknown|curl|HTML)" | wc -l) -gt 0 ]; then
    echo "WEATHER UNAVAILABLE"
else
    echo "$weather" | awk '{print $2""$3}' && dunstify "Weather" "$short"
fi
